Makefile, README.md, services/metadata/backend/data/db.json
=> feat(metadata-service): add json-server with example metadata (BS-11)

public/global.css, services/metadata/frontend/Header.svelte, services/metadata/frontend/content/Category.svelte, services/metadata/frontend/content/Content.svelte, services/metadata/frontend/content/Pagination.svelte, services/metadata/frontend/content/Tile.svelte, services/metadata/frontend/content/stores.ts
resolves BS-40
Added also some styling adjustments to previously created components.
=> feat(metadata-service): add pagination component (BS-40)

.github/pull_request_template.md, services/metadata/frontend/Header.svelte, services/metadata/frontend/content/Category.svelte, services/metadata/frontend/content/Pagination.svelte, services/metadata/frontend/content/stores.ts
=> feat(metadata-service): add basic search functionality (DSP-1482)

services/metadata/backend/data/db.json, services/metadata/frontend/Header.svelte, services/metadata/frontend/project-page/ProjectPage.svelte, services/metadata/frontend/project-page/ProjectWidget.svelte, services/metadata/frontend/projects-repository/Tile.svelte, services/metadata/frontend/stores.ts
=> feat(metadata-service): add projects (DSP-1454)

public/global.css, services/metadata/frontend/Header.svelte, services/metadata/frontend/project-page/DefaultTabComponent.svelte, services/metadata/frontend/project-page/DownloadWidget.svelte, services/metadata/frontend/project-page/ProjectPage.svelte, services/metadata/frontend/project-page/ProjectWidget.svelte, services/metadata/frontend/project-page/Tab.svelte, services/metadata/frontend/projects-repository/Pagination.svelte, services/metadata/frontend/projects-repository/ProjectsRepository.svelte, services/metadata/frontend/projects-repository/Tile.svelte, services/metadata/frontend/stores.ts
=> feat(metadata-service): FE improvements (DSP-1578)

services/metadata/frontend/stores.ts
=> fix(metadata-service): distinguish API call in envs

docs/services/metadata/example.json, docs/services/metadata/schema-metadata.json
=> docs(metadata-service): update API specification to improve multi language text representation (DSP-1419)

services/metadata/backend/fake-backend/data/reforme-geneve-metadata.json, services/metadata/frontend/project-page/DefaultTabComponent.svelte, services/metadata/frontend/project-page/ProjectPage.svelte, services/metadata/frontend/project-page/ProjectWidget.svelte
=> fix(metadata-service): attributions & spatial coverage display (DSP-1598)

services/admin/backend/api/handler/project.go, services/admin/backend/infrastructure/repository/project/project.go, services/admin/backend/infrastructure/repository/project/project_test.go, services/admin/backend/service/project/inmem_test.go, services/admin/backend/service/project/interface.go, services/admin/backend/service/project/project.go, services/admin/backend/service/project/project_test.go
=> refactor(project): Do no return deleted projects by default when listing projects (DSP-1613)

public/global.css, services/metadata/frontend/App.svelte, services/metadata/frontend/Footer.svelte, services/metadata/frontend/Snackbar.svelte, services/metadata/frontend/project-page/DefaultTabComponent.svelte, services/metadata/frontend/project-page/ProjectPage.svelte, services/metadata/frontend/project-page/ProjectWidget.svelte, services/metadata/frontend/project-page/Tab.svelte, services/metadata/frontend/projects-repository/Tile.svelte, services/metadata/frontend/store.ts
=> !feat(metadata-service): added basic snackbar handling (DSP-1598)

services/metadata/backend/fake-backend/data/cache-metadata.json, services/metadata/frontend/projects-repository/ProjectsRepository.svelte, services/metadata/frontend/projects-repository/Tile.svelte
=> fix!(metadata-service): data + styles

Makefile
=> fix!: release please action

services/metadata/frontend/App.svelte, services/metadata/frontend/Snackbar.svelte, services/metadata/frontend/project-page/ProjectPage.svelte, services/metadata/frontend/projects-repository/ProjectsRepository.svelte, services/metadata/frontend/store.ts
=> fix(metadata-service): snackbar handling + responsiveness

services/admin/backend/api/handler/project.go
=> refactor(project): return auto-generated fields in create project JSON response (DSP-1665)

services/admin/backend/api/handler/project.go, services/admin/backend/service/project/interface.go, services/admin/backend/service/project/project.go, services/admin/backend/service/project/project_test.go
=> feat(project): add migration endpoint (DSP-1666)

public/index.html, rollup.config.js, services/metadata/frontend/App.svelte, services/metadata/frontend/Header.svelte, services/metadata/frontend/Matomo.svelte, services/metadata/frontend/project-page/DefaultTabComponent.svelte, services/metadata/frontend/project-page/ProjectPage.svelte, services/metadata/frontend/project-page/ProjectWidget.svelte, services/metadata/frontend/project-page/Tab.svelte, services/metadata/frontend/projects-repository/Pagination.svelte, services/metadata/frontend/projects-repository/ProjectsRepository.svelte, services/metadata/frontend/projects-repository/Tile.svelte, services/metadata/frontend/store.ts
=> feat(metadata-service): add Mamoto tracker (DSP-1671)

README.md, services/admin/backend/api/handler/project.go, services/admin/backend/service/project/project.go, services/admin/backend/service/project/project_test.go
=> feat(project): unique and valid short codes (DSP-1685)

services/admin/backend/api/handler/project.go, services/admin/backend/api/presenter/project.go
=> refactor(project): All project operations should return entire project state (DSP-1686)

rollup.config.js, services/metadata/frontend/Matomo.svelte, services/metadata/frontend/project-page/ProjectPage.svelte, services/metadata/frontend/project-page/ProjectWidget.svelte, services/metadata/frontend/projects-repository/ProjectsRepository.svelte, services/metadata/frontend/projects-repository/Tile.svelte, services/metadata/frontend/store.ts
=> fix(metadata-service): fix Matomo configuration (DSP-1671)

services/admin/backend/api/handler/project.go, services/admin/backend/api/presenter/project.go, services/admin/backend/event/project.go, services/admin/backend/infrastructure/repository/project/project.go, services/admin/backend/service/project/project.go
=> chore(project): add more descriptive method comments (DSP-1680)

services/metadata/frontend/Matomo.svelte, services/metadata/frontend/project-page/ProjectPage.svelte, services/metadata/frontend/projects-repository/ProjectsRepository.svelte, services/metadata/frontend/projects-repository/Tile.svelte, services/metadata/frontend/store.ts
=> fix(metadata-service): fix Matomo config (DSP-1671)

services/metadata/frontend/Matomo.svelte, services/metadata/frontend/projects-repository/ProjectsRepository.svelte
=> chore(metadata-service): enable Matomo on PROD only (DSP-1671)

public/index.html
=> chore(metadata-service): add Google Analytics (DSP-1687)

services/metadata/backend/fake-backend/fake-backend.go, services/metadata/frontend/Footer.svelte
=> feat(metadata-service): add version number display (DSP-1712)

services/metadata/frontend/CookiesModal.svelte, services/metadata/frontend/cookies-service.ts
=> feat(metadata-service): set domain cookie (DSP-1704)

services/metadata/frontend/cookies-service.ts
=> fix(metadata-service): fix cookie domain (DSP-1704)

services/admin/backend/infrastructure/repository/project/project_test.go, services/admin/backend/service/project/interface.go, services/admin/backend/service/project/project.go, services/admin/backend/service/project/project_test.go
=> refactor(project): refactor unit tests (DSP-1616)

services/admin/backend/api/handler/project.go, services/admin/backend/entity/project/error.go, services/admin/backend/infrastructure/repository/project/project.go, services/admin/backend/service/project/inmem_test.go, services/admin/backend/service/project/project.go
=> chore(project): clean up error handling (DSP-1619)

services/metadata/frontend/project-page/ProjectPage.svelte
=> fix(metadata): relocate go-back-button for mobile (DSP-1682)

public/index.html
=> chore(metadata): add Fathom analytics (DSP-1735)

services/metadata/frontend/Footer.svelte, services/metadata/frontend/Header.svelte
=> fix(metadata): header and footer display for desktops (DSP-1722)

package-lock.json, package.json, public/admin/BUILD.bazel, public/admin/keycloak.json, services/admin/frontend/Projects.svelte, services/admin/frontend/store.ts, yarn.lock
=> feat(admin-gui): keycloak authentication (DSP-1760)

deps.bzl, go.mod, go.sum, public/admin/BUILD.bazel, rollup.config.js, services/admin/backend/api/handler/BUILD.bazel, services/admin/backend/api/handler/project.go, services/admin/frontend/AdminServices.svelte, services/admin/frontend/Header.svelte, services/admin/frontend/Modal/Content.svelte, services/admin/frontend/Modal/Dialog.svelte, services/admin/frontend/ProjectPage.svelte, services/admin/frontend/Projects.svelte, services/admin/frontend/interfaces.ts, services/admin/frontend/store.ts
=> feat(admin-service): admin service authorization (DSP-1772)

README.md, docs/includes/_admin-service.md, docs/includes/_deployment-configuration.md, docs/index.html.md
=> docs: update slate docs (DSP-1781)

public/metadata/index.html, services/metadata/frontend/CookiesBanner.svelte, services/metadata/frontend/Footer.svelte
EULA link has been removed. In addition I've fixed version indention to be equal with header logo.
=> fix(metadata): remove EULA link

public/metadata/BUILD.bazel, services/metadata/backend/fake-backend/BUILD.bazel
=> fix: fix bazel setup so that data is included in metadata docker image (DSP-1793)
